### PR TITLE
Import diesel locally in the generated code

### PR DESCRIPTION
**Pull request by weiznich**
This removes the contrain that extern crate diesel must be called at
the crate root

### CODE REVIEW

**Comment by quodlibetor** [comment]
One comment because I haven't seen this pattern, but otherwise this looks great!

**Comment by killercup** [comment]
Wow, that's a pretty interesting pattern, I hadn't seen this trick before!

What's the deal with using `const`? Does this have any special meaning? Other than that, I'm surprised you don't need a `use self::diesel` anywhere. (Can you maybe add some tests that show you can use this with an `extern crate diesel as foo;`?)

**Comment by weiznich** [comment]
@killercup I've only looked how [serde did handle](https://github.com/serde-rs/serde/blob/master/serde_derive/src/de.rs#L55) this and copied the pattern from there.

**Comment by quodlibetor** [comment]
`extern crate` does expose the name locally, so that seems safe.

I think the `it_builds` test can be modified to verify this works correctly by moving the `MyId` struct into a mod, otherwise we might just be accepting the global diesel name.

It seems like the `const` might be there primarily to act as a comment? I don't know of any way to include comments in the output of the `quote!` macro. I would bet @dtolnay either came up with that idiom or knows why it exists.

**Comment by quodlibetor** [comment]
@weiznich if modify the `it_builds` test to put the struct in some `mod nested { ... }` and then tell me that `cargo test` passes I'll be happy to merge this. (I plan on setting up Travis when I get back in front of a computer next week)

**Comment by dtolnay** [comment]
Yes I came up with the idiom. As far as I know, this is still the only reliable way to simultaneously satisfy the following expectations:

- Impl block has access to everything that is in scope at the location of the derive.
- Impl block has access to public APIs from diesel.
- User is not required to provide `extern crate diesel` in their crate root.
- Derive may be used multiple times within the same scope.

There is actually one better way that I have been meaning to write up for a while—maybe I can get to it in the next few days. The approach in this PR still requires the user to list diesel in their Cargo.toml even if it is otherwise not used in their code. Essentially it involves a trick to make all the diesel APIs you need accessible as `diesel_newtype::FromSql` etc, then using `extern crate diesel_newtype` inside the const block instead.

**Comment by quodlibetor** [comment]
@dtolnay I originally tried doing a `pub use diesel::...` in here but I ran into something like a "proc macro libs can only export proc macros" error. Is there a way around that that you can point me in the direction of?

**Comment by dtolnay** [comment]
You would do it backwards. Proc-macro crates cannot export non proc-macro things, but non proc-macro crates can export proc macros. See [here](https://github.com/dtolnay/proc-macro-hack/blob/0.3.3/demo-hack/src/lib.rs#L8-L12) for example. So the derive logic would move to a different crate, and diesel-newtype would export those derive macros as well as the necessary things from diesel. Users' Cargo.toml only needs to include diesel-newtype, not diesel if they are not using it directly.

Up to you whether you think the tradeoff makes sense for diesel-newtype. Macros 2.0 will solve this in a better way where basically the expanded code can use things that are in scope in the proc macro crate without worrying about what is in scope in the user's crate.

**Comment by quodlibetor** [comment]
Woah, consider my mind blown.

It does seem unlikely that anyone would care about being able to use this specific crate without diesel, it mostly just felt cleaner. I can imagine other uses that would be made nicer by that, though, thanks!

**Comment by killercup** [comment]
FYI opened <https://github.com/weiznich/diesel-newtype/pull/1> with some "compile tests"

**Comment by quodlibetor** [comment]
Awesome, yeah that's exactly the kind of evidence that I wanted. I look forward to fixing that test with some trait impls.

**Pull request merged**
